# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valve_design_desktop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(573, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy(
                                        ).hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy(
                                         ).hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vlv1_frame = QtWidgets.QFrame(self.centralwidget)
        self.vlv1_frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vlv1_frame.sizePolicy(
                                        ).hasHeightForWidth())
        self.vlv1_frame.setSizePolicy(sizePolicy)
        self.vlv1_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.vlv1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vlv1_frame.setObjectName("vlv1_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.vlv1_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vlv1_button = QtWidgets.QPushButton(self.vlv1_frame)
        self.vlv1_button.setObjectName("vlv1_button")
        self.verticalLayout.addWidget(self.vlv1_button)
        self.vlv1_lcdNumber = QtWidgets.QLCDNumber(self.vlv1_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vlv1_lcdNumber.sizePolicy(
                                      ).hasHeightForWidth())
        self.vlv1_lcdNumber.setSizePolicy(sizePolicy)
        self.vlv1_lcdNumber.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        self.vlv1_lcdNumber.setFont(font)
        self.vlv1_lcdNumber.setObjectName("vlv1_lcdNumber")
        self.verticalLayout.addWidget(self.vlv1_lcdNumber)
        spacerItem = QtWidgets.QSpacerItem(72, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.vlv1_frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vlv1_verticalSlider = QtWidgets.QSlider(self.widget)
        self.vlv1_verticalSlider.setEnabled(True)
        self.vlv1_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.vlv1_verticalSlider.setObjectName("vlv1_verticalSlider")
        self.vlv1_verticalSlider.setEnabled(False)
        self.vlv1_verticalSlider.cl
        self.horizontalLayout.addWidget(self.vlv1_verticalSlider)
        self.verticalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.vlv1_frame)
        self.vlv2_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vlv2_frame.sizePolicy(
                                         ).hasHeightForWidth())
        self.vlv2_frame.setSizePolicy(sizePolicy)
        self.vlv2_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.vlv2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vlv2_frame.setObjectName("vlv2_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.vlv2_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vlv2_button = QtWidgets.QPushButton(self.vlv2_frame)
        self.vlv2_button.setObjectName("vlv2_button")
        self.verticalLayout_2.addWidget(self.vlv2_button)
        self.vlv2_lcdNumber = QtWidgets.QLCDNumber(self.vlv2_frame)
        self.vlv2_lcdNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.vlv2_lcdNumber.setObjectName("vlv2_lcdNumber")
        self.verticalLayout_2.addWidget(self.vlv2_lcdNumber)
        spacerItem2 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.widget1 = QtWidgets.QWidget(self.vlv2_frame)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vlv2_verticalSlider = QtWidgets.QSlider(self.widget1)
        self.vlv2_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.vlv2_verticalSlider.setObjectName("vlv2_verticalSlider")
        self.vlv2_verticalSlider.setEnabled(False)
        self.horizontalLayout_2.addWidget(self.vlv2_verticalSlider)
        self.verticalLayout_2.addWidget(self.widget1)
        spacerItem3 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.vlv2_frame)
        self.vlv3_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vlv3_frame.sizePolicy(
                                      ).hasHeightForWidth())
        self.vlv3_frame.setSizePolicy(sizePolicy)
        self.vlv3_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.vlv3_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vlv3_frame.setObjectName("vlv3_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.vlv3_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vlv3_button = QtWidgets.QPushButton(self.vlv3_frame)
        self.vlv3_button.setObjectName("vlv3_button")
        self.verticalLayout_3.addWidget(self.vlv3_button)
        self.vlv3_lcdNumber = QtWidgets.QLCDNumber(self.vlv3_frame)
        self.vlv3_lcdNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.vlv3_lcdNumber.setObjectName("vlv3_lcdNumber")
        self.verticalLayout_3.addWidget(self.vlv3_lcdNumber)
        spacerItem4 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)
        self.widget2 = QtWidgets.QWidget(self.vlv3_frame)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vlv3_verticalSlider = QtWidgets.QSlider(self.widget2)
        self.vlv3_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.vlv3_verticalSlider.setObjectName("vlv3_verticalSlider")
        self.vlv3_verticalSlider.setEnabled(False)
        self.horizontalLayout_3.addWidget(self.vlv3_verticalSlider)
        self.verticalLayout_3.addWidget(self.widget2)
        spacerItem5 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_5.addWidget(self.vlv3_frame)
        self.vlv4_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vlv4_frame.sizePolicy(
                                        ).hasHeightForWidth())
        self.vlv4_frame.setSizePolicy(sizePolicy)
        self.vlv4_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.vlv4_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vlv4_frame.setObjectName("vlv4_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.vlv4_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vlv4_button = QtWidgets.QPushButton(self.vlv4_frame)
        self.vlv4_button.setObjectName("vlv4_button")
        self.verticalLayout_4.addWidget(self.vlv4_button)
        self.vlv4_lcdNumber = QtWidgets.QLCDNumber(self.vlv4_frame)
        self.vlv4_lcdNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.vlv4_lcdNumber.setObjectName("vlv4_lcdNumber")
        self.verticalLayout_4.addWidget(self.vlv4_lcdNumber)
        spacerItem6 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem6)
        self.widget3 = QtWidgets.QWidget(self.vlv4_frame)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.vlv4_verticalSlider = QtWidgets.QSlider(self.widget3)
        self.vlv4_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.vlv4_verticalSlider.setObjectName("vlv4_verticalSlider")
        self.vlv4_verticalSlider.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.vlv4_verticalSlider)
        self.verticalLayout_4.addWidget(self.widget3)
        spacerItem7 = QtWidgets.QSpacerItem(72, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_5.addWidget(self.vlv4_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow",
                                             "Valve monster comander desktop"))
        self.vlv1_button.setText(_translate("MainWindow", "VALVE1 ON"))
        self.vlv2_button.setText(_translate("MainWindow", "VALVE2 ON"))
        self.vlv3_button.setText(_translate("MainWindow", "VALVE3 ON"))
        self.vlv4_button.setText(_translate("MainWindow", "VALVE4 ON"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
